apiVersion: aws.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    backend: ${vault_aws_secret_backend.aws.path}
    credentialType: iam_user
    name: deploy
    policyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*"
          }
        ]
      }
