---
apiVersion: v1
kind: ConfigMap
metadata:
  name: upjet-provider-vault-agent-cfg
  namespace: crossplane-system
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "resourcesv2"
        }
      }
      sink "file" {
        config = {
          path = "/tmp/.vault-token"
          mode = 0666
        }
      }
    }
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upjet-provider-vault
spec:
  package: tfgco/upjet-provider-vault:1.0.0
  controllerConfigRef:
    name: upjet-provider-vault-config
---
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: upjet-provider-vault
spec:
  address: http://vault-internal.vault.svc.cluster.local:8200
  #address: https://internal-vault.wildlife.io
  skip_tls_verify: true
  credentials:
    source: Filesystem
    fs:
      path: /tmp/.vault-token
      #path: /Users/marcus.brocaneli/GolandProjects/upjet-provider-vault/.vault-token
---
apiVersion: pkg.crossplane.io/v1beta1
kind: ControllerConfig
metadata:
  name: upjet-provider-vault-config
spec:
  metadata:
    annotations:
      vault.security.banzaicloud.io/vault-role: "resourcesv2"
      vault.security.banzaicloud.io/vault-agent-configmap: upjet-provider-vault-agent-cfg
      vault.security.banzaicloud.io/vault-configfile-path: /tmp/
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
