apiVersion: kubernetesauthbackendrole.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: hello-crossplane
spec:
  forProvider:
    backend: kubernetes
    boundServiceAccountNames:
    - test-role
    boundServiceAccountNamespaces:
    - default
  providerConfigRef:
    name: default
