apiVersion: kubernetesauthbackendrole.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: brocamonster-group
spec:
  forProvider:
    backend: kubernetes-infra-prod-us-east-1
    boundServiceAccountNames:
    - brocamonster
    boundServiceAccountNamespaces:
    - default
  providerConfigRef:
    name: upjet-provider-vault
